// Instagram highlight categories for SparklebySalika
window.CATEGORIES = [
  { label: "Featured", slug: "featured", match: "Featured", count: 17 },
  { label: "2026", slug: "2026", match: "2026" },
  { label: "Limited Edition", slug: "limited-edition", match: "Limited Edition" },
  { label: "Quotes", slug: "quotes", match: "Qoutes" },
  { label: "Artists Speaks", slug: "artists-speaks", match: "Artists Speaks" },
  { label: "Reviews 2", slug: "reviews-2", match: "Reviews 2" },
  { label: "Metal Work", slug: "metal-work", match: "Metal Work" },
  { label: "Crochet", slug: "crochet", match: "Crochet" },
  { label: "Beadwork", slug: "beadwork", match: "Beadwork" },
  { label: "Clay", slug: "clay", match: "Clay" },
  { label: "Events 2", slug: "events-2", match: "Events 2" },
  { label: "Stone Work", slug: "stone-work", match: "Stone Work" },
  { label: "Reviews", slug: "reviews", match: "Reviews" },
  { label: "Resin Art", slug: "resin-art", match: "Resin Art" },
  { label: "Highlights", slug: "highlights", match: "Highlights" },
  { label: "Events", slug: "events", match: "Events" },
  { label: "Screen Printed", slug: "screen-printed", match: "Screen Printed" },
  { label: "Macramé", slug: "macrame", match: "Macram" },
  { label: "Sea Shells", slug: "sea-shells", match: "Sea Shells" },
  { label: "Art", slug: "art", match: "Art" },
  { label: "Paper Craft", slug: "paper-craft", match: "Paper Craft" },
  { label: "Decorative Art", slug: "decorative-art", match: "Decorative Art" },
  { label: "Menswear", slug: "menswear", match: "Menswear" },
  { label: "New", slug: "new", match: "New" },
  { label: "Leather", slug: "leather", match: "Leather" },
  { label: "Wood", slug: "wood", match: "Wood" },
  { label: "Wire Wrapped", slug: "wire-wrapped", match: "Wire Wrapped" },
  { label: "Pose", slug: "pose", match: "Pose" },
  { label: "Movement", slug: "movement", match: "Movement" },
  { label: "IGTV", slug: "igtv", match: "IGTV" },
  { label: "Graphic Design", slug: "graphic-design", match: "Graphic Design" },
  { label: "Redbubble", slug: "redbubble", match: "Redbubble" }
];
